CREATE DATABASE AUTO;

CREATE TABLE CLIENTS(
CLIENT_ID INT PRIMARY KEY,
FNAME VARCHAR(11) ,
LNAME VARCHAR (11),
PHONE VARCHAR (11)
);

CREATE TABLE CARS(
CAR_ID INT PRIMARY KEY,
BRAND VARCHAR(20),
MODEL VARCHAR(20),
YEAR DATE ,
PRICE DECIMAL
);

CREATE TABLE RENTALS (
CAR_ID INT,
CLIENT_ID INT,
RENTAL_DATE DATE,
RETURN_DATE DATE
PRIMARY KEY (CAR_ID,CLIENT_ID,RENTAL_DATE),
FOREIGN KEY (CLIENT_ID) REFERENCES CLIENTS (CLIENT_ID),
FOREIGN KEY (CAR_ID) REFERENCES CARS (CAR_ID)
);

ALTER TABLE CARS
ADD FUEL_TYPE VARCHAR(8) CHECK(FUEL_TYPE IN('petrol','diesel','electric'))


INSERT CLIENTS VALUES(1,'VLADO','KOLEV','0876565')
INSERT CARS VALUES(1,'BMW','M5','2024-22-10',20000)
INSERT RENTALS VALUES(1,1,'2024-22-10','2024-23-11')

DELETE FROM CARS
WHERE CAR_ID=1;




SELECT 
(c.BRAND + ' ' + c.MODEL) AS CARS,
r.CAR_ID AS INDEFICATOR,
r.RENTAL_DATE AS RENTAL_DATE,
r. RETURN_DATE AS RETURN_DATE 
FROM RENTALS r
JOIN CARS c ON  r.CAR_ID = (c.CAR_ID)
ORDER BY  r.RETURN_DATE ASC;


SELECT 
CONCAT(c.FNAME , ' ', c.LNAME) AS NAMES,
COUNT(r.CAR_ID) AS RENTAL
FROM CLIENTS c
LEFT JOIN  RENTALS r  ON c.CLIENT_ID =r.CLIENT_ID
GROUP BY c.FNAME,c.LNAME;


CREATE VIEW CarRentalsCount AS
SELECT
    c.CAR_ID,
    c.BRAND,
    c.MODEL,
    COUNT(r.CAR_ID) AS RENTAL_COUNT
FROM CARS c
JOIN RENTALS r ON c.CAR_ID = r.CAR_ID
GROUP BY c.CAR_ID, c.BRAND, c.MODEL
HAVING COUNT(r.CAR_ID) > 1;
