CREATE DATABASE MUSIC;



CREATE TABLE ARTISTS (
ARTIST_ID  INT PRIMARY KEY ,
NAME  VARCHAR(15),
GENRE VARCHAR(20)
);



CREATE TABLE ALBUMS (
ALBUM_ID INT PRIMARY KEY ,
TITLE VARCHAR(20),
RELEASE_YEAR DATE ,
ARTIST_ID INT
 FOREIGN KEY ( ARTIST_ID ) REFERENCES ARTISTS (ARTIST_ID)
);

CREATE TABLE PLAYLISTS (
PLAYLIST_ID INT PRIMARY KEY ,
NAME VARCHAR(15),
DESCRIPTION  VARCHAR(25)
);

ALTER TABLE ARTISTS 
ADD GENRE  VARCHAR(10) CHECK(GENRE IN('rock','pop','jazz'))



INSERT INTO ARTISTS VALUES(1,'IVAN','pop')
INSERT INTO ALBUMS VALUES(1,'lOVE','2025-10-11',1)
INSERT INTO PLAYLISTS VALUES(1,'GRAMSRAM','GRAM V RAQ')


DELETE FROM ALBUMS
WHERE ALBUM_ID=(SELECT MAX(ALBUM_ID)
                FROM ALBUMS);



SELECT 
    ALBUMS.TITLE AS ALBUM_TITLE,
    ARTISTS.NAME AS ARTIST_NAME,
    ALBUMS.RELEASE_YEAR
FROM ALBUMS
JOIN ARTISTS ON ALBUMS.ARTIST_ID = ARTISTS.ARTIST_ID
ORDER BY ALBUMS.RELEASE_YEAR ASC;


CREATE TABLE PLAYLIST_ALBUMS (
    PLAYLIST_ID INT,
    ALBUM_ID INT,
    FOREIGN KEY (PLAYLIST_ID) REFERENCES PLAYLISTS(PLAYLIST_ID),
    FOREIGN KEY (ALBUM_ID) REFERENCES ALBUMS(ALBUM_ID)
);

INSERT INTO PLAYLIST_ALBUMS VALUES(1,1);

SELECT *
FROM ARTISTS;

SELECT 
    P.PLAYLIST_ID,
    P.NAME AS PLAYLIST_NAME,
    COUNT(PA.ALBUM_ID) AS ALBUM_COUNT 
FROM PLAYLISTS P
LEFT JOIN PLAYLIST_ALBUMS PA ON P.PLAYLIST_ID = PA.PLAYLIST_ID
GROUP BY P.PLAYLIST_ID, P.NAME;




CREATE VIEW ARTIST_ALBUM_COUNT AS
SELECT 
    A.ARTIST_ID,
    A.NAME AS ARTIST_NAME,
    COUNT(AL.ALBUM_ID) AS ALBUM_COUNT
FROM ARTISTS A
JOIN ALBUMS AL ON A.ARTIST_ID = AL.ARTIST_ID
GROUP BY A.ARTIST_ID, A.NAME
HAVING COUNT(AL.ALBUM_ID) >= 1;

