CREATE DATABASE RESTURANTS2;

CREATE TABLE CUSTOMERS(
CUSTOMER_ID INT PRIMARY KEY,
FNAME VARCHAR(10),
LNAME VARCHAR(10),
PHONE VARCHAR(11)
);


CREATE TABLE MENU_ITEMS(
ITEM_ID INT  PRIMARY KEY,
ITEM_NAME VARCHAR(21),
CATEGORY VARCHAR(15),
PRICE DECIMAL
);

CREATE TABLE ORDERS(
CUSTOMER_ID  INT,
ITEM_ID  INT,
ORDER_DATE DATE,
QUANTITY  INT
PRIMARY KEY (CUSTOMER_ID,ITEM_ID,ORDER_DATE)
FOREIGN KEY (CUSTOMER_ID) REFERENCES CUSTOMERS (CUSTOMER_ID),
FOREIGN KEY (ITEM_ID) REFERENCES MENU_ITEMS (ITEM_ID)
);

ALTER TABLE ORDERS
ADD  STATUS VARCHAR(10) CHECK(STATUS IN ('pending','served','paid'))


 INSERT INTO  CUSTOMERS VALUES(1,'VANKATA','PETKOV','0876296597')
 INSERT INTO MENU_ITEMS VALUES(1,'pizza','junkfood',20)
 INSERT INTO ORDERS VALUES(1,1,'2025-10-01',10)

 DELETE MENU_ITEMS
 WHERE ITEM_NAME =1;

 SELECT 
 CONCAT(c.FNAME, '', c.LNAME) AS NAME,
 m.ITEM_NAME AS DISH_NAME,
 o.ORDER_DATE AS ORDER_DATE
 FROM ORDERS o
 JOIN CUSTOMERS c ON c.CUSTOMER_ID = o.CUSTOMER_ID
 JOIN MENU_ITEMS m ON m.ITEM_ID = o.ITEM_ID
 ORDER BY o.ORDER_DATE ASC;

 SELECT 
 CONCAT(c.FNAME, '', c.LNAME) AS NAME,
 COUNT(o.CUSTOMER_ID) AS PORUCKI
 FROM CUSTOMERS c
 LEFT JOIN ORDERS o ON  c.CUSTOMER_ID = o.CUSTOMER_ID
 GROUP BY c.FNAME, c.LNAME;

 CREATE VIEW DishOrderCount AS
SELECT 
    m.ITEM_ID,
    m.ITEM_NAME,
    COUNT(o.ITEM_ID) AS TOTAL_ORDERS
FROM MENU_ITEMS m
JOIN ORDERS o ON m.ITEM_ID = o.ITEM_ID
GROUP BY m.ITEM_ID, m.ITEM_NAME
HAVING COUNT(o.ITEM_ID) > 1;