
SELECT CITY, COUNT(DEPARTMENT_ID) AS NUM_DEPARTMENTS
FROM DEPARTMENTS
GROUP BY CITY
ORDER BY NUM_DEPARTMENTS DESC


SELECT FNAME, LNAME, EMAIL
FROM EMPLOYEES
WHERE DEPARTMENT_ID IS NULL AND EMAIL LIKE 'k%'


SELECT J.JOB_TITLE, COUNT(E.EMPLOYEE_ID) AS NUM_EMPLOYEES
FROM EMPLOYEES E
JOIN JOBS J ON E.JOB_ID = J.JOB_ID
GROUP BY J.JOB_TITLE
HAVING COUNT(E.EMPLOYEE_ID) BETWEEN 1 AND 5
ORDER BY NUM_EMPLOYEES 

