CREATE TABLE STUDENTS (
    F_NUM VARCHAR(10) PRIMARY KEY,
    NAME VARCHAR(50),
    PHONE VARCHAR(15),
    GENDER CHAR(1) CHECK(GENDER IN ('M', 'F'))
)

CREATE TABLE COURSES (
    COURSE_ID INT PRIMARY KEY,
    NAME VARCHAR(100) NOT NULL,
    HORARIUM  INT CHECK(HORARIUM > 10 AND HORARIUM < 100),
    START_DATE DATE CHECK(START_DATE > '2023-10-01'),
    END_DATE DATE
)


CREATE TABLE STUDENT_COURSES (
    COURSE_ID INT,
    F_NUM VARCHAR(10),

    CONSTRAINT PK_STUDENT_COURSES PRIMARY KEY (COURSE_ID, F_NUM),
    CONSTRAINT FK_SC_COURSE FOREIGN KEY (COURSE_ID) REFERENCES COURSES(COURSE_ID),
    CONSTRAINT FK_SC_STUDENT FOREIGN KEY (F_NUM) REFERENCES STUDENTS(F_NUM)
)


INSERT INTO STUDENTS(F_NUM, NAME, PHONE, GENDER) 
VALUES ('123456', 'Vladimir ', '0876296598', 'M')


INSERT INTO COURSES(COURSE_ID, NAME, HORARIUM, START_DATE, END_DATE) 
VALUES (1, 'Databases', 40, '2023-10-15', '2024-01-15');


INSERT INTO STUDENT_COURSES(COURSE_ID, F_NUM)
VALUES (1, '2401681022');


UPDATE COURSES
SET HORARIUM = HORARIUM + 10
WHERE COURSE_ID = 1;


SELECT DATEDIFF(WEEK, START_DATE, END_DATE) AS WEEKS_DIFF
FROM COURSES
WHERE COURSE_ID = 1;

DELETE FROM STUDENTS WHERE F_NUM = '2401681022';







