CREATE DATABASE Zadacha1;

CREATE TABLE GP(

GP_ID INT PRIMARY KEY ,
FNAME VARCHAR(50)   NOT NULL,
LNAME  VARCHAR (50) NOT NULL,
ADRESS  VARCHAR (40)NOT NULL,
PHONE  VARCHAR (30) NULL

);

CREATE TABLE PATIENT (
PATIENT_ID INT PRIMARY KEY,
FNAME VARCHAR(50)  NOT NULL,
LNAME  VARCHAR (50)NOT NULL,
GENDER VARCHAR(1) NOT NULL CHECK (GENDER IN  ('M', 'F')),
BIRTHDATE date,
EGN  VARCHAR (10) NOT NULL UNIQUE,
GP_ID INT NOT NULL,
CONSTRAINT FK_PATIENT_GP FOREIGN KEY (GP_ID)
REFERENCES GP(GP_ID)




);

INSERT INTO GP (GP_ID,FNAME,LNAME,ADRESS,PHONE)
VALUES (1,'IVANKA','IVANOVA','ORFEI2','08762698');


INSERT INTO PATIENT (PATIENT_ID,FNAME,LNAME,GENDER,BIRTHDATE,EGN,GP_ID)
VALUES(1,'Nikolay','POPOV','M','1998-05-10','0545172360',1);

